name: Sync graphics drivers branches

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'

jobs:
  integrate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Sync
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin 
          for branch in amd nvidia intel; do
            git checkout -B "$branch" "origin/$branch"
            if git merge origin/main --no-edit -X theirs; then
              git push origin "$branch"
            else
              exit 1 
            fi
          done